### ISSUE TITLE
aws-sdk-go ?

### ISSUE THREAD

**Issue by porjo** [goamz/goamz#114]
Why would I use goamz in preference to the official SDK for Go: [aws-sdk-go](https://github.com/aws/aws-sdk-go)?

It would be good to add to the README a brief explanation for newcomers. Thanks.

**Comment by boyand** [comment]
Ideally you should use the official SDK that Amazon supports if it works for you. Goamz has been started years before there was any official Golang support and has been helping the community to utilise AWS services. Currently it is still used in a lot of applications and quite well battle tested. Therefore we try best to maintain it but ideally people should be moving to the official AWS SDK if the functionality they seek is there.
