### ISSUE TITLE
Support for IAM ListServerCertificates

### ISSUE THREAD

**Issue by rosenhouse** [goamz/goamz#69]
Has anyone begun working on this functionality in the IAM client?  We're considering starting to implement it.

API Documentation: http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListServerCertificates.html

**Comment by boyand** [comment]
Hey @rosenhouse, 

I am not aware of anyone working on that atm. It would be fantastic if you can implement it and pr it back.

**Comment by rosenhouse** [comment]
Gotcha.  Will update this thread if we decide to pick it up.
